version:2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - Run:
          name: Install Python dependencies
          command : |
            pip install --user -r requirements.txt
workflows:
  build:
    jobs:
      - build
